//DECLARO LAS ACCIONES COMO STRINGS Y EXPORTO 
const INCREMENTO = 'INCREMENTO';
const DECREMENTO = 'DECREMENTO';
const INCREMENTO_IMPAR = 'INCREMENTOIMPAR';
const INCREMENTO_ASYNC = 'INCREMENTOS_ASYNC';

module.exports = {
  INCREMENTO,
  DECREMENTO,
  INCREMENTO_IMPAR,
  INCREMENTO_ASYNC
}